export const HTTP_SUCCESS_CODES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  PARTIAL_CONTENT: 206
}

export const HTTP_CLIENT_ERROR_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  NOT_ACCEPTABLE: 406,
  CONFLICT: 409,
  UNSUPPORTED_MEDIA_TYPE: 415,
  UNPROCESSABLE_ENTITY: 422,
  TOO_EARLY: 425,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431
}

export const HTTP_SERVER_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511
}

export type CLIENT_SUCCESS_CODE = typeof HTTP_SUCCESS_CODES[keyof typeof HTTP_SUCCESS_CODES]

export type CLIENT_ERROR_CODE = typeof HTTP_CLIENT_ERROR_CODES[keyof typeof HTTP_CLIENT_ERROR_CODES]

export type SERVER_ERROR_CODE = typeof HTTP_SERVER_ERROR_CODES[keyof typeof HTTP_SERVER_ERROR_CODES]
